/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardPermintaanKebutuhanDapurRouteImport } from './routes/dashboard/permintaan-kebutuhan-dapur'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardLaporanIndexRouteImport } from './routes/dashboard/laporan.index'
import { Route as DashboardAkunAnggotaIndexRouteImport } from './routes/dashboard/akun-anggota.index'
import { Route as DashboardAkunAdminIndexRouteImport } from './routes/dashboard/akun-admin.index'
import { Route as DashboardLaporanIdRouteImport } from './routes/dashboard/laporan.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPermintaanKebutuhanDapurRoute =
  DashboardPermintaanKebutuhanDapurRouteImport.update({
    id: '/dashboard/permintaan-kebutuhan-dapur',
    path: '/dashboard/permintaan-kebutuhan-dapur',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLaporanIndexRoute = DashboardLaporanIndexRouteImport.update({
  id: '/dashboard/laporan/',
  path: '/dashboard/laporan/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAkunAnggotaIndexRoute =
  DashboardAkunAnggotaIndexRouteImport.update({
    id: '/dashboard/akun-anggota/',
    path: '/dashboard/akun-anggota/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAkunAdminIndexRoute = DashboardAkunAdminIndexRouteImport.update({
  id: '/dashboard/akun-admin/',
  path: '/dashboard/akun-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLaporanIdRoute = DashboardLaporanIdRouteImport.update({
  id: '/dashboard/laporan/$id',
  path: '/dashboard/laporan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/permintaan-kebutuhan-dapur': typeof DashboardPermintaanKebutuhanDapurRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/laporan/$id': typeof DashboardLaporanIdRoute
  '/dashboard/akun-admin': typeof DashboardAkunAdminIndexRoute
  '/dashboard/akun-anggota': typeof DashboardAkunAnggotaIndexRoute
  '/dashboard/laporan': typeof DashboardLaporanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/permintaan-kebutuhan-dapur': typeof DashboardPermintaanKebutuhanDapurRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/laporan/$id': typeof DashboardLaporanIdRoute
  '/dashboard/akun-admin': typeof DashboardAkunAdminIndexRoute
  '/dashboard/akun-anggota': typeof DashboardAkunAnggotaIndexRoute
  '/dashboard/laporan': typeof DashboardLaporanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/permintaan-kebutuhan-dapur': typeof DashboardPermintaanKebutuhanDapurRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/laporan/$id': typeof DashboardLaporanIdRoute
  '/dashboard/akun-admin/': typeof DashboardAkunAdminIndexRoute
  '/dashboard/akun-anggota/': typeof DashboardAkunAnggotaIndexRoute
  '/dashboard/laporan/': typeof DashboardLaporanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/dashboard/permintaan-kebutuhan-dapur'
    | '/dashboard'
    | '/dashboard/laporan/$id'
    | '/dashboard/akun-admin'
    | '/dashboard/akun-anggota'
    | '/dashboard/laporan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/dashboard/permintaan-kebutuhan-dapur'
    | '/dashboard'
    | '/dashboard/laporan/$id'
    | '/dashboard/akun-admin'
    | '/dashboard/akun-anggota'
    | '/dashboard/laporan'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/dashboard/permintaan-kebutuhan-dapur'
    | '/dashboard/'
    | '/dashboard/laporan/$id'
    | '/dashboard/akun-admin/'
    | '/dashboard/akun-anggota/'
    | '/dashboard/laporan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DashboardPermintaanKebutuhanDapurRoute: typeof DashboardPermintaanKebutuhanDapurRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLaporanIdRoute: typeof DashboardLaporanIdRoute
  DashboardAkunAdminIndexRoute: typeof DashboardAkunAdminIndexRoute
  DashboardAkunAnggotaIndexRoute: typeof DashboardAkunAnggotaIndexRoute
  DashboardLaporanIndexRoute: typeof DashboardLaporanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/permintaan-kebutuhan-dapur': {
      id: '/dashboard/permintaan-kebutuhan-dapur'
      path: '/dashboard/permintaan-kebutuhan-dapur'
      fullPath: '/dashboard/permintaan-kebutuhan-dapur'
      preLoaderRoute: typeof DashboardPermintaanKebutuhanDapurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/laporan/': {
      id: '/dashboard/laporan/'
      path: '/dashboard/laporan'
      fullPath: '/dashboard/laporan'
      preLoaderRoute: typeof DashboardLaporanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/akun-anggota/': {
      id: '/dashboard/akun-anggota/'
      path: '/dashboard/akun-anggota'
      fullPath: '/dashboard/akun-anggota'
      preLoaderRoute: typeof DashboardAkunAnggotaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/akun-admin/': {
      id: '/dashboard/akun-admin/'
      path: '/dashboard/akun-admin'
      fullPath: '/dashboard/akun-admin'
      preLoaderRoute: typeof DashboardAkunAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/laporan/$id': {
      id: '/dashboard/laporan/$id'
      path: '/dashboard/laporan/$id'
      fullPath: '/dashboard/laporan/$id'
      preLoaderRoute: typeof DashboardLaporanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  DashboardPermintaanKebutuhanDapurRoute:
    DashboardPermintaanKebutuhanDapurRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLaporanIdRoute: DashboardLaporanIdRoute,
  DashboardAkunAdminIndexRoute: DashboardAkunAdminIndexRoute,
  DashboardAkunAnggotaIndexRoute: DashboardAkunAnggotaIndexRoute,
  DashboardLaporanIndexRoute: DashboardLaporanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
