/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TentangKamiIndexRouteImport } from './routes/tentang-kami/index'
import { Route as ProfilIndexRouteImport } from './routes/profil/index'
import { Route as LaporIndexRouteImport } from './routes/lapor/index'
import { Route as DataLaporanIndexRouteImport } from './routes/data-laporan/index'
import { Route as CaraKerjaIndexRouteImport } from './routes/cara-kerja/index'
import { Route as AuthRegisterAnggotaRouteImport } from './routes/auth/register-anggota'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangKamiIndexRoute = TentangKamiIndexRouteImport.update({
  id: '/tentang-kami/',
  path: '/tentang-kami/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilIndexRoute = ProfilIndexRouteImport.update({
  id: '/profil/',
  path: '/profil/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporIndexRoute = LaporIndexRouteImport.update({
  id: '/lapor/',
  path: '/lapor/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataLaporanIndexRoute = DataLaporanIndexRouteImport.update({
  id: '/data-laporan/',
  path: '/data-laporan/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaraKerjaIndexRoute = CaraKerjaIndexRouteImport.update({
  id: '/cara-kerja/',
  path: '/cara-kerja/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterAnggotaRoute = AuthRegisterAnggotaRouteImport.update({
  id: '/auth/register-anggota',
  path: '/auth/register-anggota',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/register-anggota': typeof AuthRegisterAnggotaRoute
  '/cara-kerja': typeof CaraKerjaIndexRoute
  '/data-laporan': typeof DataLaporanIndexRoute
  '/lapor': typeof LaporIndexRoute
  '/profil': typeof ProfilIndexRoute
  '/tentang-kami': typeof TentangKamiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/register-anggota': typeof AuthRegisterAnggotaRoute
  '/cara-kerja': typeof CaraKerjaIndexRoute
  '/data-laporan': typeof DataLaporanIndexRoute
  '/lapor': typeof LaporIndexRoute
  '/profil': typeof ProfilIndexRoute
  '/tentang-kami': typeof TentangKamiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/register-anggota': typeof AuthRegisterAnggotaRoute
  '/cara-kerja/': typeof CaraKerjaIndexRoute
  '/data-laporan/': typeof DataLaporanIndexRoute
  '/lapor/': typeof LaporIndexRoute
  '/profil/': typeof ProfilIndexRoute
  '/tentang-kami/': typeof TentangKamiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/auth/register-anggota'
    | '/cara-kerja'
    | '/data-laporan'
    | '/lapor'
    | '/profil'
    | '/tentang-kami'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/auth/register-anggota'
    | '/cara-kerja'
    | '/data-laporan'
    | '/lapor'
    | '/profil'
    | '/tentang-kami'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/auth/register-anggota'
    | '/cara-kerja/'
    | '/data-laporan/'
    | '/lapor/'
    | '/profil/'
    | '/tentang-kami/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthRegisterAnggotaRoute: typeof AuthRegisterAnggotaRoute
  CaraKerjaIndexRoute: typeof CaraKerjaIndexRoute
  DataLaporanIndexRoute: typeof DataLaporanIndexRoute
  LaporIndexRoute: typeof LaporIndexRoute
  ProfilIndexRoute: typeof ProfilIndexRoute
  TentangKamiIndexRoute: typeof TentangKamiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang-kami/': {
      id: '/tentang-kami/'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/': {
      id: '/profil/'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lapor/': {
      id: '/lapor/'
      path: '/lapor'
      fullPath: '/lapor'
      preLoaderRoute: typeof LaporIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-laporan/': {
      id: '/data-laporan/'
      path: '/data-laporan'
      fullPath: '/data-laporan'
      preLoaderRoute: typeof DataLaporanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cara-kerja/': {
      id: '/cara-kerja/'
      path: '/cara-kerja'
      fullPath: '/cara-kerja'
      preLoaderRoute: typeof CaraKerjaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register-anggota': {
      id: '/auth/register-anggota'
      path: '/auth/register-anggota'
      fullPath: '/auth/register-anggota'
      preLoaderRoute: typeof AuthRegisterAnggotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthRegisterAnggotaRoute: AuthRegisterAnggotaRoute,
  CaraKerjaIndexRoute: CaraKerjaIndexRoute,
  DataLaporanIndexRoute: DataLaporanIndexRoute,
  LaporIndexRoute: LaporIndexRoute,
  ProfilIndexRoute: ProfilIndexRoute,
  TentangKamiIndexRoute: TentangKamiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
