/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TentangKamiIndexRouteImport } from './routes/tentang-kami/index'
import { Route as ProfilIndexRouteImport } from './routes/profil/index'
import { Route as LaporIndexRouteImport } from './routes/lapor/index'
import { Route as DataLaporanIndexRouteImport } from './routes/data-laporan/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CaraKerjaIndexRouteImport } from './routes/cara-kerja/index'
import { Route as AuthRegisterAnggotaRouteImport } from './routes/auth/register-anggota'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginAnggotaRouteImport } from './routes/auth/login-anggota'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardLaporanIndexRouteImport } from './routes/dashboard/laporan.index'
import { Route as DashboardAkunAnggotaIndexRouteImport } from './routes/dashboard/akun-anggota.index'
import { Route as DashboardLaporanIdRouteImport } from './routes/dashboard/laporan.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangKamiIndexRoute = TentangKamiIndexRouteImport.update({
  id: '/tentang-kami/',
  path: '/tentang-kami/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilIndexRoute = ProfilIndexRouteImport.update({
  id: '/profil/',
  path: '/profil/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporIndexRoute = LaporIndexRouteImport.update({
  id: '/lapor/',
  path: '/lapor/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataLaporanIndexRoute = DataLaporanIndexRouteImport.update({
  id: '/data-laporan/',
  path: '/data-laporan/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaraKerjaIndexRoute = CaraKerjaIndexRouteImport.update({
  id: '/cara-kerja/',
  path: '/cara-kerja/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterAnggotaRoute = AuthRegisterAnggotaRouteImport.update({
  id: '/auth/register-anggota',
  path: '/auth/register-anggota',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginAnggotaRoute = AuthLoginAnggotaRouteImport.update({
  id: '/auth/login-anggota',
  path: '/auth/login-anggota',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLaporanIndexRoute = DashboardLaporanIndexRouteImport.update({
  id: '/dashboard/laporan/',
  path: '/dashboard/laporan/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAkunAnggotaIndexRoute =
  DashboardAkunAnggotaIndexRouteImport.update({
    id: '/dashboard/akun-anggota/',
    path: '/dashboard/akun-anggota/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardLaporanIdRoute = DashboardLaporanIdRouteImport.update({
  id: '/dashboard/laporan/$id',
  path: '/dashboard/laporan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/login-anggota': typeof AuthLoginAnggotaRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/register-anggota': typeof AuthRegisterAnggotaRoute
  '/cara-kerja': typeof CaraKerjaIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/data-laporan': typeof DataLaporanIndexRoute
  '/lapor': typeof LaporIndexRoute
  '/profil': typeof ProfilIndexRoute
  '/tentang-kami': typeof TentangKamiIndexRoute
  '/dashboard/laporan/$id': typeof DashboardLaporanIdRoute
  '/dashboard/akun-anggota': typeof DashboardAkunAnggotaIndexRoute
  '/dashboard/laporan': typeof DashboardLaporanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/login-anggota': typeof AuthLoginAnggotaRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/register-anggota': typeof AuthRegisterAnggotaRoute
  '/cara-kerja': typeof CaraKerjaIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/data-laporan': typeof DataLaporanIndexRoute
  '/lapor': typeof LaporIndexRoute
  '/profil': typeof ProfilIndexRoute
  '/tentang-kami': typeof TentangKamiIndexRoute
  '/dashboard/laporan/$id': typeof DashboardLaporanIdRoute
  '/dashboard/akun-anggota': typeof DashboardAkunAnggotaIndexRoute
  '/dashboard/laporan': typeof DashboardLaporanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/login-anggota': typeof AuthLoginAnggotaRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/register-anggota': typeof AuthRegisterAnggotaRoute
  '/cara-kerja/': typeof CaraKerjaIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/data-laporan/': typeof DataLaporanIndexRoute
  '/lapor/': typeof LaporIndexRoute
  '/profil/': typeof ProfilIndexRoute
  '/tentang-kami/': typeof TentangKamiIndexRoute
  '/dashboard/laporan/$id': typeof DashboardLaporanIdRoute
  '/dashboard/akun-anggota/': typeof DashboardAkunAnggotaIndexRoute
  '/dashboard/laporan/': typeof DashboardLaporanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/login-anggota'
    | '/auth/register'
    | '/auth/register-anggota'
    | '/cara-kerja'
    | '/dashboard'
    | '/data-laporan'
    | '/lapor'
    | '/profil'
    | '/tentang-kami'
    | '/dashboard/laporan/$id'
    | '/dashboard/akun-anggota'
    | '/dashboard/laporan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/login-anggota'
    | '/auth/register'
    | '/auth/register-anggota'
    | '/cara-kerja'
    | '/dashboard'
    | '/data-laporan'
    | '/lapor'
    | '/profil'
    | '/tentang-kami'
    | '/dashboard/laporan/$id'
    | '/dashboard/akun-anggota'
    | '/dashboard/laporan'
  id:
    | '__root__'
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/login-anggota'
    | '/auth/register'
    | '/auth/register-anggota'
    | '/cara-kerja/'
    | '/dashboard/'
    | '/data-laporan/'
    | '/lapor/'
    | '/profil/'
    | '/tentang-kami/'
    | '/dashboard/laporan/$id'
    | '/dashboard/akun-anggota/'
    | '/dashboard/laporan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLoginAnggotaRoute: typeof AuthLoginAnggotaRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthRegisterAnggotaRoute: typeof AuthRegisterAnggotaRoute
  CaraKerjaIndexRoute: typeof CaraKerjaIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DataLaporanIndexRoute: typeof DataLaporanIndexRoute
  LaporIndexRoute: typeof LaporIndexRoute
  ProfilIndexRoute: typeof ProfilIndexRoute
  TentangKamiIndexRoute: typeof TentangKamiIndexRoute
  DashboardLaporanIdRoute: typeof DashboardLaporanIdRoute
  DashboardAkunAnggotaIndexRoute: typeof DashboardAkunAnggotaIndexRoute
  DashboardLaporanIndexRoute: typeof DashboardLaporanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang-kami/': {
      id: '/tentang-kami/'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/': {
      id: '/profil/'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lapor/': {
      id: '/lapor/'
      path: '/lapor'
      fullPath: '/lapor'
      preLoaderRoute: typeof LaporIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-laporan/': {
      id: '/data-laporan/'
      path: '/data-laporan'
      fullPath: '/data-laporan'
      preLoaderRoute: typeof DataLaporanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cara-kerja/': {
      id: '/cara-kerja/'
      path: '/cara-kerja'
      fullPath: '/cara-kerja'
      preLoaderRoute: typeof CaraKerjaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register-anggota': {
      id: '/auth/register-anggota'
      path: '/auth/register-anggota'
      fullPath: '/auth/register-anggota'
      preLoaderRoute: typeof AuthRegisterAnggotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login-anggota': {
      id: '/auth/login-anggota'
      path: '/auth/login-anggota'
      fullPath: '/auth/login-anggota'
      preLoaderRoute: typeof AuthLoginAnggotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/laporan/': {
      id: '/dashboard/laporan/'
      path: '/dashboard/laporan'
      fullPath: '/dashboard/laporan'
      preLoaderRoute: typeof DashboardLaporanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/akun-anggota/': {
      id: '/dashboard/akun-anggota/'
      path: '/dashboard/akun-anggota'
      fullPath: '/dashboard/akun-anggota'
      preLoaderRoute: typeof DashboardAkunAnggotaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/laporan/$id': {
      id: '/dashboard/laporan/$id'
      path: '/dashboard/laporan/$id'
      fullPath: '/dashboard/laporan/$id'
      preLoaderRoute: typeof DashboardLaporanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLoginAnggotaRoute: AuthLoginAnggotaRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthRegisterAnggotaRoute: AuthRegisterAnggotaRoute,
  CaraKerjaIndexRoute: CaraKerjaIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DataLaporanIndexRoute: DataLaporanIndexRoute,
  LaporIndexRoute: LaporIndexRoute,
  ProfilIndexRoute: ProfilIndexRoute,
  TentangKamiIndexRoute: TentangKamiIndexRoute,
  DashboardLaporanIdRoute: DashboardLaporanIdRoute,
  DashboardAkunAnggotaIndexRoute: DashboardAkunAnggotaIndexRoute,
  DashboardLaporanIndexRoute: DashboardLaporanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
